### ISSUE TITLE
Visual Studio Code is not an IDE

### ISSUE THREAD

**Issue by carloshvp** [realpython/python-guide#1021]
Hello,
For some reason, Visual Studio Code is listed under IDEs. It is even wrongly written as "Visual Studio Code IDE". VS Code is a text editor, very similar to Sublime.

If you agree with this change, I can make a pull-request.

Thank you

**Comment by atomicblue224** [comment]
Hello,
          Thank you so much. I wasn't looking for that.
                                                                                Eric

**Comment by agathavekris** [comment]
Is @carloshvp fixing this or can I try? Looking for my first issue fix haha.

**Comment by carloshvp** [comment]
Hi @agathavekris , that was my intention as well, but I was asking for some feedback before making any pull-request... if I find the time this weekend I will do a PR and ask you for feedback. Thanks!

**Comment by agathavekris** [comment]
sounds great, thank you !

**Comment by carloshvp** [comment]
Hi @agathavekris (and others), you can now have a look at the PR mentioned above. Simple change, but needed in my view. Thanks!

**Comment by agathavekris** [comment]
Hey @carloshvp . It looks great ! Although this part sounded a little funny to me:

`Python for Visual Studio is an extension for the Visual Studio Code.`

Wouldn't it sound better as this?: 

`Python for Visual Studio is an extension for the Visual Studio Code source-code editor.` 

Might be silly, but I figured I'd mention it!

**Comment by bzaczynski** [comment]
Your PR was merged a few weeks ago. Thanks for the contribution again!
