### ISSUE TITLE
macOS now comes with python3, not python2. Mac article needs complete rewrite.

### ISSUE THREAD

**Issue by sandrogisler** [realpython/python-guide#1032]
Page "https://docs.python-guide.org/starting/install3/osx/" is largely obsolete since newer versions of macOS now come with python3 built-in.

**Comment by glyph** [comment]
This is not true. macOS has a shim in /usr/bin, but the actual python3 install is in the Xcode app bundle:

```
$ /usr/bin/python3
>>> import sys
>>> sys.executable
'/Applications/Xcode.app/Contents/Developer/usr/bin/python3'
```

Testing this conclusively requires a fresh OS install, but I believe this requires the full Xcode app and isn’t present in the command line tools download.

**Comment by sandrogisler** [comment]
I apologize. I have to admit that glyph is very likely correct. I do have xcode on my machine, and it is absolutely possible that python3 came with xcode, not with the OS. I was just surprised (and excited) that python3 worked without any further ado in terminal.
I assumed falsely that it came with the OS and didn't think that it could've come with a package that I installed later.
I will attempt to close the issue.
