### ISSUE TITLE
Python 2 end of life modifications

### ISSUE THREAD

**Issue by hharutyunyan** [realpython/python-guide#1033]
As you all know, Python 2 reached the end of its life a few days ago, so I think the [page of choosing the version](https://docs.python-guide.org/starting/which-python/) should be modified. 

For instance

> Python 2.7 will only receive necessary security updates until 2020

would rather be written in past tense :)

**Comment by petschki** [comment]
A note to the OSX installation guide (https://github.com/realpython/python-guide/blob/master/docs/starting/install/osx.rst) ... the `python@2` Formula has been deleted on feb 4 2020 (see https://github.com/Homebrew/homebrew-core/pull/49796) ... according to a stackoverflow entry (https://stackoverflow.com/a/60345962/1145447) it is still possible to install it with the direkt link to the last commit to this file:

```
brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/86a44a0a552c673a05f11018459c9f5faae3becc/Formula/python@2.rb
```

**Comment by hharutyunyan** [comment]
#1068 Resolves this
