### ISSUE TITLE
Python 2 syntax in examples, why?

### ISSUE THREAD

**Issue by matheusfelipeog** [realpython/python-guide#1091]
Hi :)

Why use python 2 syntax in examples today? Since [Python 2 has been discontinued in January 1, 2020](https://www.python.org/doc/sunset-python-2/#:~:text=We%20have%20decided%20that%20January,as%20soon%20as%20you%20can.).

## Examples:

- In many examples `print "string"` syntax is used.

- In ["Create a length-N list of lists"](https://docs.python-guide.org/writing/style/#create-a-length-n-list-of-lists) is used:

```python
four_lists = [[] for __ in xrange(4)]
```
instead:

```python
four_lists = [[] for __ in range(4)]
```

Has a note stating the new syntax:

> Note: Use range() instead of xrange() in Python 3.

But is this really necessary today? Isn't it better to update everything to Python 3 syntax?

**Comment by matheusfelipeog** [comment]
If allowed, I can update everything to Python 3 syntax ;)

**Comment by dbader** [comment]
@matheusfelipeog Agreed, I think it's time to switch the Guide over to Python 3 🙂 

> If allowed, I can update everything to Python 3 syntax ;)

Well, that'd be amazing. If you want to put together a pull-request (or a series of PRs we can merge one by one) to make some of these updates that'd be great.

**Comment by matheusfelipeog** [comment]
Right 😆 

I will start the update soon.

**Comment by matheusfelipeog** [comment]
I updated everything I found 😄 

I made a pull request per updated section

**Comment by dbader** [comment]
Cheers @matheusfelipeog, I just merged those PRs :)
