### ISSUE TITLE
TODO list, preferably with priority

### ISSUE THREAD

**Issue by jabagawee** [realpython/python-guide#113]
Just wondering, can we get some sort of priority list of what to add onto the guide? On a related note, it'd be nice to see some sort of roadmap for where it's going; are we here to be, for example, an all out comprehensive wiki for all things Python?

**Comment by userlerueda** [comment]
@JensRantil do you think that there is still a need for the TODO?

**Comment by JensRantil** [comment]
I never thought a TODO was needed. Issues are enough.

**Comment by userlerueda** [comment]
Recommending we close this issue.
