### ISSUE TITLE
Update for: Distribute merged into Setuptools 0.7+

### ISSUE THREAD

**Issue by sun** [realpython/python-guide#289]
Problem
- Installation tutorial suggests to use Distribute, but Distribute has been merged into Setuptools 0.7+.

Resources
- Quoting the [latest Distribute stable release](https://pypi.python.org/pypi/distribute/0.7.3):
  
  > This package is a simple compatibility layer that installs Setuptools 0.7+.

Proposed solution
1. Replace Distribute installation instructions with just simply these commands for Setuptools:
   1. Download and install Setuptools from https://pypi.python.org/pypi/setuptools via `ez_setup.py`:
      
      ```
       $ python ez_setup.py
      ```

**Comment by userlerueda** [comment]
@sun adn @santagada if this has been integrated via #390 can it be closed?

**Comment by santagada** [comment]
@userlerueda for me yes, definitely

**Comment by userlerueda** [comment]
@kennethreitz Recommend we close this issue.
