### ISSUE TITLE
Duplicate entries for virtualenvs.

### ISSUE THREAD

**Issue by rshipp** [realpython/python-guide#457]
The documentation for virtualenvs is duplicated, with some in [dev/env](https://github.com/kennethreitz/python-guide/blob/master/docs/dev/env.rst#interpreter-tools), (for some reason under the header "Interpreter Tools") and the rest in [dev/virtualenvs](https://github.com/kennethreitz/python-guide/blob/master/docs/dev/virtualenvs.rst). Should all of the virtualenv information be put in `dev/virtualenvs`, with only a quick link from `dev/env`, or should `dev/virtualenvs` be deleted entirely and all information consolidated into `dev/env`?

**Comment by varunagrawal** [comment]
Can someone please provide input on this? I will update and submit a PR accordingly.

**Comment by userlerueda** [comment]
I think this issue can be closed, [dev/env](https://github.com/kennethreitz/python-guide/blob/master/docs/dev/env.rst#interpreter-tools) has a small paragraph and a pointer to [dev/virtualenvs](https://github.com/kennethreitz/python-guide/blob/master/docs/dev/virtualenvs.rst)
