### ISSUE TITLE
Add Packaging section on PBR

### ISSUE THREAD

**Issue by pjz** [realpython/python-guide#494]
PBR (Python Build Reasonableness) seems to be gaining a lot of ground. At least mention it and point to the [docs](http://docs.openstack.org/developer/pbr/)

**Comment by userlerueda** [comment]
Has a decision been made of whether or not to include this?

**Comment by sigmavirus24** [comment]
@userlerueda I'm not associated with this project any longer, but I would advise whomever is still maintaining this against it. This package *regularly* breaks software I use for work. Further, it appears to be barely maintained at this point. I would exclude it.

**Comment by pjz** [comment]
FWIW, two-plus years on, I'm 0 to -1 on this.
