### ISSUE TITLE
Style page implies that two pieces of list code are functionally equivalent

### ISSUE THREAD

**Issue by zaphod65** [realpython/python-guide#796]
The section on "ways to manipulate a list" has these blocks:

```python
a = [3, 4, 5]
b = [i for i in a if i > 4]
# Or:
b = filter(lambda x: x > 4, a)
```

```python
a = [3, 4, 5]
a = [i + 3 for i in a]
# Or:
a = map(lambda i: i + 3, a)
```

Which imply that the list comprehension and filter/map examples are functionally the same, when they aren't.  This could easily trip up a new user, and in the spirit of Python we should be explicit about what exactly these two examples do and mean.

**Comment by userlerueda** [comment]
@zaphod65 can you point to the url where this block is to be found ? This would be useful if later there is agreement on change.

**Comment by zaphod65** [comment]
https://github.com/kennethreitz/python-guide/blob/master/docs/writing/style.rst

Lines 595 and 613 are where the blocks begin to be exact.

**Comment by mpoulin** [comment]
Thanks @zaphod65 and @userlerueda . I've updated that section of the Guide and I am closing this issue.
