### ISSUE TITLE
Package your code to share it with other developers. ... github is missing

### ISSUE THREAD

**Issue by guettli** [realpython/python-guide#803]
The "Packing your code" chapter starts like this: 

> Package your code to share it with other developers. 

From: http://docs.python-guide.org/en/latest/shipping/packaging/#packaging-your-code

The above sentence is true, if "other developers" means "users of your library".

If you want to share code with other people who want to modify and update your code, then Packaging is not the solution.

Maybe I am hair splitting here. Both groups of audience is very different. I think sharing code gets done via github, not via pypi.

I am missing a chapter about github. I think the live cycle of code looks like this:

IDE of developer -> Upload github (Pull request) -> CI OK? -> If CI ok, then merge into master -> upload to pypi.

**Comment by kennethreitz** [comment]
A chapter on GitHub sounds great!

**Comment by apjanke** [comment]
Here's a stab at a GitHub chapter: https://github.com/realpython/python-guide/pull/963. Comments welcome.
