### ISSUE TITLE
Standardize on British or Standard American English

### ISSUE THREAD

**Issue by suchow** [realpython/python-guide#838]
I'm hoping to open a PR with many sentence-level stylistic edits. I notice that there are several places in the guide where British English is used, e.g. the "whilst" in:

> ..., whilst still using Python 3.4 as the default interpreter...

and many other places where Standard American English is used.

Is it safe to assume that the guide is intended to be written entirely in Standard American English?

**Comment by rsvp** [comment]
Most of Python is developed in the United States. 
The PEPs are never written in the Queen's English.
The O'Reilly books on Python all use American English.

But the namesake, _Monty Python_, originates from the UK.
That seems to be the sole exception I can think of.

**Comment by kennethreitz** [comment]
I think it's fine to mix, for fun's sake :)

It also shows that the book is written by other authors.

However, I wouldn't be against a PR that migrates us over to Standard American English.

**Comment by rsvp** [comment]
### Should Python code be in strictly Standard American English?

For example, it would be a hassle to grep for "color" and "colour"
in a Python graphics package.

Wondering if misunderstanding over spelling can introduce bugs,
like the length bugs in international vehicles: inches vs. centimeters.

**Comment by Nefari0uss** [comment]
Spelling is one thing and usually pretty clear what the word is. Length on the other hand is a unit of measurement and a little different...

**Comment by rsvp** [comment]
@Nefari0uss My point is about ***underlying assumptions which are taken for granted***,
but unknowingly violated by someone who does not share that *implicit* knowledge.

**Comment by dbader** [comment]
I'm be in favor of standardizing on American English for consistency's. If anybody's inclined to put together a PR let me know!

**Comment by apjanke** [comment]
Here's a PR: https://github.com/realpython/python-guide/pull/962
