### ISSUE TITLE
shipping: py2exe looks dated

### ISSUE THREAD

**Issue by guettli** [realpython/python-guide#911]
You still list py2exe here:

https://docs.python-guide.org/shipping/freezing/

The latest "News" entry on the homepage of py2exe is from 2008. Today ten years old.

The latest release is four years old.

I think it is wise to warn the user about this.

**Comment by dbader** [comment]
I agree! Would you be interested in putting together a PR to update that section?

**Comment by guettli** [comment]
@dbader I added a simple hint. OK?

**Comment by dbader** [comment]
Thanks @guettli! Any ideas as to which tool we could recommend instead?

**Comment by guettli** [comment]
@dbbrian I think cx_freeze is more alive. But I only used it once (three days ago)

**Comment by dbbrian** [comment]
@guettli I think you meant @dbader ;)

**Comment by dbader** [comment]
> @dbader I think cx_freeze is more alive. But I only used it once (three days ago)

@guettli Ok, well if you feel inspired to add a little writeup about `cx_freeze` feel free to send another PR :)
