### ISSUE TITLE
Dive into Python 3 Website is down

### ISSUE THREAD

**Issue by shlomihod** [realpython/python-guide#926]
It seems that the link to the book "Dive into Python 3" is not available anymore:
http://www.diveintopython3.net/

I made a [fork](https://github.com/ProblemSolvingIO/diveintopython3) to the [repo](https://github.com/diveintomark/diveintopython3) and published it with GitHub Pages in that URL in case you would like to update the link:
http://diveintopython3.problemsolving.io

**Comment by mpoulin** [comment]
Thanks for the updated link @shlomihod .

**Comment by mpoulin** [comment]
Fixed. Closing this issue.
