### ISSUE TITLE
W3C link checker warnings, https://docs.python-guide.org/

### ISSUE THREAD

**Issue by mpoulin** [realpython/python-guide#928]
Links that redirect to newer pages should be updated.
Many of these seem to be simple http --> https changes.

Processing	https://docs.python-guide.org/

List of redirects
The links below are not broken, but the document does not use the exact URL, and the links were redirected. It may be a good idea to link to the final location, for the sake of speed.

warning Line: 547 http://python-guide-pt-br.readthedocs.io/pt_BR/latest/ redirected to https://python-guide-pt-br.readthedocs.io/pt_BR/latest/
Status: 301 -> 200 OK
This is a permanent redirect. The link should be updated.

warning Line: 544 http://python-guideja.readthedocs.io/ja/latest/ redirected to https://python-guideja.readthedocs.io/ja/latest/
Status: 301 -> 200 OK
This is a permanent redirect. The link should be updated.

warning Line: 546 http://python-guide-fil.readthedocs.io/en/latest/ redirected to https://python-guide-fil.readthedocs.io/en/latest/
Status: 301 -> 200 OK
This is a permanent redirect. The link should be updated.

warning Line: 567 http://kennethreitz.com/pages/open-projects.html redirected to https://www.kennethreitz.org/projects
Status: 301 -> 200 OK
This is a permanent redirect. The link should be updated.

warning Line: 567 http://creativecommons.org/licenses/by-nc-sa/3.0/ redirected to https://creativecommons.org/licenses/by-nc-sa/3.0/
Status: 301 -> 200 OK
This is a permanent redirect. The link should be updated.

**Comment by apjanke** [comment]
How did you run the W3C link checker? I tried sticking `https://docs.python-guide.org/` into the field at https://www.w3.org/2007/OWL/draft/tr-checks/checklinks-13-owl2-dr-linear.html but it's giving me a 404 Not Found error.

**Comment by mpoulin** [comment]
@apjanke 
I got the same error. This link seems to work:
https://validator.w3.org/checklink

**Comment by apjanke** [comment]
That works. Thank you!
