### ISSUE TITLE
[doc website] Add nice search experience

### ISSUE THREAD

**Issue by s-pace** [realpython/python-guide#932]
👋 team,

I'm working at Algolia on the a project called [DocSearch](https://community.algolia.com/docsearch/) which goal is to enhance documentation websites with exhaustive, fast and relevant search. You might have seen DocSearch live already on websites like [Bootstrap](https://getbootstrap.com/), [ESLint](https://eslint.org/) or [Babel](https://babeljs.io/).

We put together [a demo](https://python-guide-docsearch.surge.sh/) of what DocSearch on the python-guide website could look like here. Feel free to try it and let us know what you think. Please not the learn-as-you-type experience and the typo tolerance:

[![demo of DocSearch + python-guide](https://cl.ly/b2f5d4ada0ad/download/Screen%20Recording%202018-11-07%20at%2011.41%20AM.gif)](https://python-guide-docsearch.surge.sh/)

The way DocSearch works is by crawling your content, pushing the results into an Algolia index, and then requesting this index directly from the website front-end through JavaScript.

We'll take care of crawling your website and populating the Algolia index with the latest changes every 24h for you. You don't need to change anything to your deployment process. The only thing you need to add are the following CSS and JS snippets that will bind the dropdown to your searchbox.

```html
<!-- at the end of the HEAD -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/docsearch.js@2/dist/cdn/docsearch.min.css" />

<!-- at the end of the BODY -->
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/docsearch.js@2/dist/cdn/docsearch.min.js"></script>
<script type="text/javascript"> docsearch({
  apiKey: '512b0d6c0c8578bed7662f5279c2249c',
  indexName: 'python-guide',
  inputSelector: '### REPLACE ME ####',
  debug: false // Set debug to true if you want to inspect the dropdown
});
</script>
```

The `inputSelector` option should be set to a CSS selector that target your search input. Feel free to update it if this one is not specific enough.

We built DocSearch with the idea of giving back to the Open-Source community. This is why your [crawling configuration](https://github.com/algolia/docsearch-configs/blob/master/configs/python-guide.json) is available on GitHub if you want to change it. We also have our own [documentation](https://community.algolia.com/docsearch/documentation/) to help you tweak the dropdown to your needs. You'll also have access to *analytics on the most searched terms* or those with *no results*. All of this is of course *entirely free*.

Would that be something you'd be interested in? If so, we'd be happy to work on integrating it through a PR.

**Comment by dbader** [comment]
Hi @s-pace, wow this is super snappy and looks great. Yeah I'd love to integrate this into the site, if you can go ahead and put together a quick PR that'd be fantastic. Thanks!

**Comment by s-pace** [comment]
🎉 @dbader 

Do not forget to send us an email at docsearch@algolia.com. I will give you access to the analytics :)

**Comment by dbader** [comment]
Thanks again @s-pace, closing this :)
