### ISSUE TITLE
Expand data serialization section

### ISSUE THREAD

**Issue by dbader** [realpython/python-guide#938]
https://docs.python-guide.org/scenarios/serialization/#what-is-data-serialization

Some ideas:

* JSON serialization
* XML serialization
* YAML

**Comment by mpoulin** [comment]
@dbader 
Here's a rough outline of what this section might look like.

* Definition of serialization
* Decide if your data is flat or nested
* Data formats
    * Text
        * simple file (flat data) : use print(repr(data)) and ast.literal_eval() to safely write and parse text
        * CSV file (flat data) : use the Python CSV module
        * YAML (nested data) : use a 3rd party module
        * JSON file (nested data) : use the Python JSON module
        * XML (nested data) : use the Python XML module
    * Binary
        * lists of numbers (flat data) : use the Python `array` module
        * pickle/shelve (nested data) : use the Python pickle and shelve modules

**Comment by harishkrao** [comment]
Is this still available/open? If yes, can I take this?

**Comment by mpoulin** [comment]
@harishkrao Yes, please take it.

**Comment by harishkrao** [comment]
@mpoulin, I am committing changes for this issue in a feature branch. I am trying to push changes to the feature branch remote and I am receiving a permission denied. Can I get access to push to remote feature branches in this repository please? Thanks.

**Comment by mpoulin** [comment]
Hi @harishkrao .
It's a 2 step process. Here's how it works:
1. Contributors (you) make changes and create a "pull request"
2. Maintainers (Dan or I) run some automated validation tests on the pull request and do the actual commit.

Hope that helps.
Marc

**Comment by harishkrao** [comment]
Thank you for explaining the merge/commit process @mpoulin. I am working on completing the component. I will create a pull request soon.

**Comment by harishkrao** [comment]
Hi @mpoulin, thank you for merging my pull request. I do not have access to do it, so can someone with access, close this issue please?
