### ISSUE TITLE
pipenv is the suggested tool to create isolated python environments

### ISSUE THREAD

**Issue by abhisunkewar** [realpython/python-guide#948]
It is a best practice to use **pipenv** rather than **virtualenv** although virtualenv is widely used. pipenv just makes things easier to deal with and is also secure.

**Comment by zachvalenta** [comment]
not so clear cut

https://medium.com/@grassfedcode/five-myths-about-pipenv-698c5f198e4b

> Myth 2: “Pipenv is the officially recommended Python packaging tool from Python.org”

> This myth comes from older versions of Pipenv’s documentation. The claim is misleading because it sounds like a recommendation from the core Python team but is actually referring to a recommendation from the Python Packaging Authority (PyPA), a volunteer organization separate from core Python with no qualifications for membership [1]. Pipenv now more accurately markets itself as a tool for application dependency management, not for all Python packaging. Pipenv is still recommended in the PyPA’s documentation (which is slightly controversial) among other tools, but it’s not the packaging tool for all of Python.

**Comment by nad2000** [comment]
hasn't pipenv collapsed on itself and died from own complexity yet?

**Comment by zachvalenta** [comment]
There's been a lot of discussion in this space lately

* https://jacobian.org/2018/feb/21/python-environment-2018/
* https://medium.com/@grassfedcode/five-myths-about-pipenv-698c5f198e4b
* https://hynek.me/articles/python-app-deps-2018/
* https://medium.com/@dbkats/state-of-python-in-2018-68fe478f8bb6

Seems too early to draw conclusions but excited to see how things turn out!

**Comment by return42** [comment]
pipenv is build on top of  virtualenv and pip [setup.py required](https://github.com/pypa/pipenv/blob/master/setup.py#L24)
