### ISSUE TITLE
Reconsider recommending map over list comprehensions

### ISSUE THREAD

**Issue by gbrova** [realpython/python-guide#968]
Currently the examples in the [structure section](https://docs.python-guide.org/writing/structure/#mutable-and-immutable-types) imply a list comprehension is "Better"

```
# create a concatenated string from 0 to 19 (e.g. "012..1819")
nums = [str(n) for n in range(20)]
print "".join(nums)
```

but using map is "Best"

```
# create a concatenated string from 0 to 19 (e.g. "012..1819")
nums = map(str, range(20))
print "".join(nums)
```

However, the guide doesn't recommend one approach over the other in the [style section](https://docs.python-guide.org/writing/style/#modifying-the-values-in-a-list). 

My impression is most people prefer list comprehensions because they are cleaner even if sometimes microscopically slower. See e.g. a [discussion on StackOverflow](https://stackoverflow.com/questions/1247486/list-comprehension-vs-map) and Google's [style guide](http://google.github.io/styleguide/pyguide.html#215-deprecated-language-features). 

Is it intentional to recommend `map` over list comprehensions?  If yes, we should add this recommendation in the style section for consistency; if not, we should remove the recommendation in the structure section.  FWIW, my preference is list comprehensions.

**Comment by dbader** [comment]
Good point—also related to this discussion:

[Guido seems to prefer list comps over map/filter](https://www.artima.com/weblogs/viewpost.jsp?thread=98196)

**Comment by mpoulin** [comment]
@dbader @gbrova 
It seems to me that Python is evolving in the direction of iterators and lazy evaluation. Many of the built-in functions that returned lists in 2.x now return iterators in 3.x.

I think the recommendation should be
* Use generator expressions when you don't need to capture the entire output sequence.
* Use list comprehensions in the few cases when you really need to create a second list.
* Use generator functions when the logic is too complicated for a generator or comprehension.

Lastly, never use a list comprehension just for its side effects.

BAD:
```
[print(x) for x in seqeunce]
```
BEST:
```
for x in sequence:
    print(x)
```

**Comment by gbrova** [comment]
That's a good point about lazy evaluation and generator expressions. 

Should I throw together a PR?

**Comment by mpoulin** [comment]
Yes, I would like to see what you come up with 👍
