### ISSUE TITLE
diveintopython.net no longer exists

### ISSUE THREAD

**Issue by davidshq** [realpython/python-guide#984]
In Structuring Your Project one of the recommended resources is diveintopython.net, however this site no longer exists (errr, its a domain sale page). Perhaps the link should be removed or replaced with Archive.org's cached copy? https://web.archive.org/web/20171225023735/http://www.diveintopython.net/toc/index.html

**Comment by mpoulin** [comment]
Hi @davidshq

This link works
https://www.diveinto.org/python3/

Would you like to update the URL and create a pull request?

**Comment by davidshq** [comment]
I've opened pull request #987 with this and some other small updates.

**Comment by mpoulin** [comment]
PR merged and issue closed.
