### ISSUE TITLE
Best practice for keeping a translated fork up-to-date with the english version

### ISSUE THREAD

**Issue by SebastianoF** [realpython/python-guide#986]
Hi there!!

I'm planning to start the journey of translating python-guide in Italian.
From what I can understand, to add a new language one should:

+ fork the repo
+ translate on a new branch of the forked repo
+ publish on readthedocs.com the translated version
+ add the link to the published doc on the master
+ send a PR to have the link included in the mainstream version.

Is this the best way to go? 

If yes, if the original english repo changes, how do I know from my forked version and the translated branch I created, what parts have changed (and so what do I have to re-translate)? Is there a way to say the reader which version of the original repo is he/she reading?

Thanks in advance!!

**Comment by mpoulin** [comment]
Have you seen the Google translation service at https://translate.google.com ?

1. Click the "Text" button (not "Documents")
2. Paste the https://docs.python-guide.org/ into the left box. 
3. Choose "English" on the left and "Italian" on the right.
4. Click the link in the right box. You should see the entire website translated into Italian.

What to you think of the quality? Can you tell it is a machine translation?

**Comment by SebastianoF** [comment]
Yes, you can definitely tell it is a machine translation (the title would be amusingly translated back into something like "The guide to python by mr Hitchhiker"). Nonetheless, it is not bad at all. I guess you saved me a load of time!
